version: "3"
services:
  seq:
    image: datalust/seq:2023.2
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    volumes:
      - C:\docker\seq:/data
    networks:
      job_seeker_network:
        ipv4_address: 172.20.0.2

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: unless-stopped
    networks:
      job_seeker_network:
        ipv4_address: 172.20.0.3
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - C:\docker\rabbitmq:/var/lib/rabbitmq

  postgres:
    image: postgres:15.3
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=jobseeker
      - POSTGRES_PASSWORD=jobseeker
    ports:
      - 5432:5432
    volumes:
      - C:\docker\postgresql:/var/lib/postgresql/data
    networks:
      job_seeker_network:
        ipv4_address: 172.20.0.4

  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos-standalone-mysql
    env_file:
      - ./env/nacos-standlone-mysql.env
    volumes:
      - C:\docker\nacos\standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      job_seeker_network:
        ipv4_address: 172.20.0.5

  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./image/mysql/8/Dockerfile
    image: nacos/mysql:8.0.30
    env_file:
      - ./env/mysql.env
    volumes:
      - C:\docker\mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped
    networks:
      job_seeker_network:
        ipv4_address: 172.20.0.6

networks:
  job_seeker_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16