name: Job-Seeker-CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Set up date and time
        id: datetime
        run: echo "DATE=$(date +'%Y%m%d.%H%M')" >> $GITHUB_ENV

      - name: Build Docker image - Crawer - 104
        run: |
          docker build -f ./Crawer_104/Dockerfile -t arisuokay/job-seeker-crawer-104:${{ env.DATE }} -t arisuokay/job-seeker-crawer-104:latest .

      - name: Build Docker image - Crawer - CakeResume
        run: |
          docker build -f ./Crawer_CakeResume/Dockerfile -t arisuokay/job-seeker-crawer-cakeresume:${{ env.DATE }} -t arisuokay/job-seeker-crawer-cakeresume:latest .

      - name: Build Docker image - Web
        run: |
          docker build -f ./Web/Dockerfile -t arisuokay/job-seeker-web:${{ env.DATE }} -t arisuokay/job-seeker-web:latest .
